var items = {
	food: {
		0: {cost:10000, prodcost: 5, chickenout: 100, name: "Regular Food", description: "Something good. Your chicken will like it and be in good health.", karma: 10},	
		1: {cost:10000, prodcost: 3, chickenout: 100, name: "Proteins", description: "Made with parts of animals we can't sell. We put it in a big machine, and powder comes out. You didn't know chicken were carnivore ? We didn't know either, but thanks to us we made science progress are paying a lot less !", karma: -10},
	},
	farm: {
		0: {cost:80000, prodcost: 5, chickenout: 800, name: "Free-range", description: "A nice farm, with a lot of space for chicken to run and live with each others. They can see light but you will produce less because you need more space for them.", karma: 100},
		1: {cost:70000, prodcost: 2, chickenout: 1400, name: "Indoor", description: "The Council for Agricultural Science and Technology (CAST) states that the minimum space is one-half square foot per bird.<br/>The air can become highly polluted with ammonia from the droppings. This can damage the chickens’ eyes and respiratory systems and can cause painful burns on their legs (called hock burns) and feet. Broilers bred for fast growth have a high rate of leg deformities because the large breast muscles causes distortions of the developing legs and pelvis, and the birds cannot support their increased body weight. Because they cannot move easily, the chickens are not able to adjust their environment to avoid heat, cold or dirt as they would in natural conditions. The added weight and overcrowding also puts a strain on their hearts and lungs and Ascites can develop. In the UK, up to 19 milion broilers die in their sheds from heart failure each year.", karma: -80},
		2: {cost:80000, prodcost: 4, chickenout: 1000, name: "Indoor with higher welfare", description: "Chickens are kept indoors but with more space (around 12 to 14 birds per square metre). They have a richer environment for example with natural light or straw bales that encourage foraging and perching. The chickens grow more slowly and live for up to two weeks longer than intensively farmed birds. The benefits of higher welfare indoor systems are the reduced growth rate, less crowding and more opportunities for natural behaviour..", karma: -40},
		3: {cost:80000, prodcost: 6, chickenout: 500, name: "Organic Farm", description: "Organic broiler chickens are reared under similar conditions to free-range broilers but with restrictions on the routine use of in-feed or in-water medications, other food additives and synthetic amino acids. The breeds used are slower growing, more traditional breeds and typically reach slaughter weight at around 12 weeks of age. They have a larger space allowance outside (at least 2 square metres and sometimes up to 10 square metres per bird). The Soil Association standards indicate a maximum outdoors stocking density of 2,500 birds per hectare and a maximum of 1,000 broilers per poultry house.", karma: 100},
	},
	marketing:{
		0: {cost:10000, prodcost: -1, chickenout: 0, name: "Truck packing", description: "We used trucks before to sell chickens to the market. But now we can pack chicken a lot, so we can sell a lot more!", karma: -10},	
		1: {cost:10000, prodcost: -2, chickenout: -50, name: "Chick culling", description: "A male is born. Just kill him, he produces no eggs, and food is not that good. Reduce your production cost, since you have one less beak to bread.<br/><br/>In industrial factory farms, chicks that are not intended for rearing are culled shortly after their sex is determined, usually before they are 72 hours old. About 200 million male chicks are killed each year in the United States.<br/>The American Veterinary Medical Association recommends cervical dislocation and asphyxiation by carbon dioxide as the best options, but has recently amended their guidelines to include maceration.", karma: -20},	
		2: {cost:10000, prodcost: -1, chickenout: 0, name: "Battery Cage", description: "Pack more, sell more. Increase your chicken output at a low cost.", karma: -30},	
	},
	health:{
		0: {cost:5000, prodcost: 0, chickenout: 100, name: "Beak trimming", description: "We seen that chicken were doing some cannibalism, feather picking and aggression. This is not our fault, they are just stupid creatures. So we just remove the beak of the chicken! They don't need it anyway. And to make it cheap, we do not use anesthetic.<br/>Laying hens are routinely beak-trimmed at 1 day of age to reduce the damaging effects of aggression, feather pecking and cannibalism. Scientific studies have shown that beak trimming is likely to cause both acute and chronic pain.", karma: -50},	
		1: {cost:5000, prodcost: 1, chickenout: 400, name: "Antibiotics", description: "Cheap way to bread your chicken. They don't need to eat anything else, antibiotics are great ! It may reduce effectiveness over humans but hey, if they keep eating chicken they would stay under treatment ! No risk, guarantee<br/><br/>In October 2000, the U.S. Food and Drug Administration (FDA) discovered that two antibiotics were no longer effective in treating diseases found in factory-farmed chickens.", karma: -30},
		2: {cost:8000, prodcost: 0, chickenout: 800, name: "Arsenic", description: "You chicken grows faster! Arsenic is toxic to humans, and go into the chicken meat. But the amount of arsenic is so low, we are allowed to sell it.<br/>Used by 70% of the chicken industry.", karma: -40},
	}
};